#!/bin/bash
# =============================================================================
# restart.sh - Restart all services
# =============================================================================
# Restarts all Docker Compose services including dynamically generated
# worker/runner compose files and external service stacks.
#
# Handles compose files via build_compose_files_array() from utils.sh:
#   - docker-compose.yml (main)
#   - docker-compose.n8n-workers.yml (if exists and n8n profile active)
#   - docker-compose.ollama-instances.yml (if exists and an Ollama profile active)
#   - docker-compose.ollama-gpu-devices.yml (if gpu-nvidia profile active and OLLAMA_GPU_DEVICES set)
#   - docker-compose.invokeai-gpu-devices.yml (if invokeai-nvidia profile active and INVOKEAI_GPU_DEVICES set)
#   - docker-compose.comfyui-gpu-devices.yml (if comfyui-nvidia profile active and COMFYUI_GPU_DEVICES set)
#   - docker-compose.open-webui-postgres.yml (if open-webui profile active and OPEN_WEBUI_DATABASE=postgres)
#   - supabase/docker/docker-compose.yml (if exists and supabase profile active)
#   - dify/docker/docker-compose.yaml (if exists and dify profile active)
#   - docker-compose.override.yml (if exists, user overrides with highest precedence)
#
# Usage: bash scripts/restart.sh
# =============================================================================

set -e

# Source the utilities file and initialize paths
source "$(dirname "$0")/utils.sh"
init_paths

cd "$PROJECT_ROOT"

# Load environment to check active profiles
load_env

# Keep the Supabase API gateway bound to loopback (issue #108). restart.sh runs
# neither 03_generate_secrets.sh nor prepare_supabase_env(), so the documented
# 'git pull' + 'make restart' path needs this explicitly.
harden_supabase_gateway_bind

PROJECT_NAME="localai"

# Set when a compose override that .env asks for is missing. Without this the
# run ends on "Services restarted successfully!" and the earlier error scrolls
# away - on a non-interactive run the tail is all anyone reads.
DEGRADED=0

# Time to wait for external services (Supabase, Dify) to initialize before starting main stack
EXTERNAL_SERVICE_INIT_DELAY=10

# Build compose files array (sets global COMPOSE_FILES)
build_compose_files_array

# Ensure postiz.env exists if Postiz is enabled (required for volume mount)
# This is a safety net for cases where restart runs without start_services.py
# (e.g., git pull + make restart instead of make update)
if is_profile_active "postiz"; then
    if [ -d "$PROJECT_ROOT/postiz.env" ]; then
        log_warning "postiz.env exists as a directory (created by Docker). Removing and recreating as file."
        rm -rf "$PROJECT_ROOT/postiz.env"
        touch "$PROJECT_ROOT/postiz.env"
    elif [ ! -f "$PROJECT_ROOT/postiz.env" ]; then
        log_warning "postiz.env not found, creating empty file. Run 'make update' to generate full config."
        touch "$PROJECT_ROOT/postiz.env"
    fi
fi

# Same safety net: the Crawl4AI token is generated by 'make update', not by
# restart. Without it Crawl4AI 0.9+ binds loopback only and other containers
# cannot reach it, while the container still looks healthy.
if is_profile_active "crawl4ai" && [ -z "${CRAWL4AI_API_TOKEN:-}" ]; then
    log_warning "CRAWL4AI_API_TOKEN is empty - Crawl4AI will be unreachable from other containers. Run 'make update' to generate the token."
fi

# The pre-1.13 'comfyui' profile matches no service any more. Compose accepts
# an unknown profile silently, and 'down' leaves the old container running as
# an orphan, so ComfyUI would look alive while still on the old CPU-only setup.
if is_profile_active "comfyui"; then
    log_warning "The 'comfyui' profile was replaced by comfyui-nvidia / comfyui-amd / comfyui-cpu in 1.13 - ComfyUI will NOT be restarted by this command. Run 'make update' to pick the hardware profile."
fi

log_info "Restarting services..."
log_info "Using compose files: ${COMPOSE_FILES[*]}"

# Stop all services using ALL compose files (including external stacks)
# This ensures clean shutdown of everything before restart
docker compose -p "$PROJECT_NAME" "${COMPOSE_FILES[@]}" down

# Start services in correct order (matching start_services.py behavior)
# NOTE: External stacks (Supabase, Dify) must be started SEPARATELY because their
# compose files use relative paths for volumes/configs. When combined with main
# docker-compose.yml via -f flags, the relative paths resolve incorrectly.
# Solution: Start external stacks first from their own directories, then start main stack.

if is_profile_active "supabase"; then
    SUPABASE_COMPOSE="$PROJECT_ROOT/supabase/docker/docker-compose.yml"
    if [ -f "$SUPABASE_COMPOSE" ]; then
        log_info "Starting Supabase services..."
        docker compose -p "$PROJECT_NAME" -f "$SUPABASE_COMPOSE" up -d
        log_info "Waiting for Supabase to initialize..."
        sleep "$EXTERNAL_SERVICE_INIT_DELAY"
    fi
fi

if is_profile_active "dify"; then
    DIFY_COMPOSE="$PROJECT_ROOT/dify/docker/docker-compose.yaml"
    if [ -f "$DIFY_COMPOSE" ]; then
        log_info "Starting Dify services..."
        docker compose -p "$PROJECT_NAME" -f "$DIFY_COMPOSE" up -d
        log_info "Waiting for Dify to initialize..."
        sleep "$EXTERNAL_SERVICE_INIT_DELAY"
    fi
fi

# Build main compose files (exclude external stacks that were started separately)
MAIN_COMPOSE_FILES=("-f" "$PROJECT_ROOT/docker-compose.yml")
if path=$(get_n8n_workers_compose); then
    MAIN_COMPOSE_FILES+=("-f" "$path")
fi
if path=$(get_ollama_instances_compose); then
    MAIN_COMPOSE_FILES+=("-f" "$path")
elif ollama_instances_missing; then
    DEGRADED=1
fi
if path=$(get_ollama_gpu_devices_compose); then
    MAIN_COMPOSE_FILES+=("-f" "$path")
fi
if path=$(get_invokeai_gpu_devices_compose); then
    MAIN_COMPOSE_FILES+=("-f" "$path")
fi
if path=$(get_comfyui_gpu_devices_compose); then
    MAIN_COMPOSE_FILES+=("-f" "$path")
fi
if path=$(get_open_webui_postgres_compose); then
    MAIN_COMPOSE_FILES+=("-f" "$path")
elif is_profile_active "open-webui" && [ "${OPEN_WEBUI_DATABASE:-}" = "postgres" ]; then
    # build_compose_files_array already logged the full explanation above; only
    # record it here so the closing line cannot claim an unqualified success.
    DEGRADED=1
fi
OVERRIDE_COMPOSE="$PROJECT_ROOT/docker-compose.override.yml"
if [ -f "$OVERRIDE_COMPOSE" ]; then
    MAIN_COMPOSE_FILES+=("-f" "$OVERRIDE_COMPOSE")
fi

# Start main services
log_info "Starting main services..."
docker compose -p "$PROJECT_NAME" "${MAIN_COMPOSE_FILES[@]}" up -d

if [ "$DEGRADED" -eq 0 ]; then
    log_success "Services restarted successfully!"
else
    log_warning "Services restarted, but the stack is NOT what .env describes - see the errors above."
fi
